// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Netcest_Desktop;
//
//    var felhasznalok = Felhasznalok.FromJson(jsonString);

namespace Netcest_Desktop
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Felhasznalok
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("nev")]
        public string Nev { get; set; }

        [JsonProperty("elerhetoseg")]
        public string Elerhetoseg { get; set; }

        [JsonProperty("allapot")]
        public string Allapot { get; set; }

        [JsonProperty("role")]
        public string Role { get; set; }
    }

    public partial class Felhasznalok
    {
        public static List<Felhasznalok> FromJson(string json) => JsonConvert.DeserializeObject<List<Felhasznalok>>(json, Netcest_Desktop.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<Felhasznalok> self) => JsonConvert.SerializeObject(self, Netcest_Desktop.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
