// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using CyberNest_Admin;
//
//    var foglalas = Foglalas.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace CyberNest_Admin
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    public partial class Foglalas
    {
        [JsonPropertyName("id")]
        public int Id { get; set; }

        [JsonPropertyName("felhasznalo_id")]
        public int FelhasznaloId { get; set; }

        [JsonPropertyName("eszkoz_id")]
        public int EszkozId { get; set; }

        [JsonPropertyName("idopont_id")]
        public int IdopontId { get; set; }

        [JsonPropertyName("berlesi_kezdete")]
        public DateTimeOffset BerlesiKezdete { get; set; }

        [JsonPropertyName("berlesi_vege")]
        public DateTimeOffset BerlesiVege { get; set; }

        [JsonPropertyName("mentor_id")]
        public string MentorId { get; set; }

        [JsonPropertyName("mentor_nev")]
        public string MentorNev { get; set; }

        [JsonPropertyName("ugyfel_nev")]
        public string UgyfelNev { get; set; }

        [JsonPropertyName("szamlazasi_nev")]
        public string SzamlazasiNev { get; set; }

        [JsonPropertyName("email")]
        public string Email { get; set; }

        [JsonPropertyName("telefon")]
        //[JsonConverter(typeof(ParseStringConverter))]
        public string Telefon { get; set; }

        [JsonPropertyName("megjegyzes")]
        public string Megjegyzes { get; set; }

        [JsonPropertyName("foglalas_datuma")]
        public DateTimeOffset FoglalasDatuma { get; set; }

        [JsonPropertyName("felhasznalo_nev")]
        public string FelhasznaloNev { get; set; }

        [JsonPropertyName("elerhetoseg")]
        public string Elerhetoseg { get; set; }

        [JsonPropertyName("cpu")]
        public string Cpu { get; set; }

        [JsonPropertyName("ram")]
        public string Ram { get; set; }

        [JsonPropertyName("hdd")]
        public string Hdd { get; set; }

        [JsonPropertyName("eszkoz_leiras")]
        public string EszkozLeiras { get; set; }
        public static List<Foglalas> FoglalasAll = new List<Foglalas>();
    }

    public partial class Foglalas
    {
        public static List<Foglalas> FromJson(string json) => JsonSerializer.Deserialize<List<Foglalas>>(json, CyberNest_Admin.Converter.Settings);
    }

    public static class FoglalasSerialize
    {
        public static string ToJsonFoglalas(this List<Foglalas> self) => JsonSerializer.Serialize(self, CyberNest_Admin.Converter.Settings);
    }

    
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
